	.file	"sseTest.c"
	.section	.rodata.str1.1,"aMS",@progbits,1
.LC7:
	.string	"|%g %g| * |%g %g| = |%g %g|\n"
.LC8:
	.string	"|%g %g|   |%g %g|   |%g %g|\n"
	.section	.text.startup,"ax",@progbits
	.p2align 4,,15
	.globl	main
	.type	main, @function
main:
.LFB532:
	.cfi_startproc
	subq	$88, %rsp
	.cfi_def_cfa_offset 96
	xorpd	%xmm6, %xmm6
	movsd	.LC0(%rip), %xmm0 
	movl	$.LC7, %edi       
	movsd	.LC1(%rip), %xmm7
	movl	$6, %eax
	movsd	%xmm0, 16(%rsp)
	movsd	%xmm7, 24(%rsp)
	movsd	%xmm6, 48(%rsp)
	movsd	%xmm6, 56(%rsp)
	movsd	%xmm6, 64(%rsp)
	movsd	%xmm6, 72(%rsp)
	movsd	.LC2(%rip), %xmm1
	movsd	.LC3(%rip), %xmm7
	/*starting the loop cycle*/
	movupd	16(%rsp), %xmm2   /* this function was generated by the intrinsic function 					    _mm_loadu_pd */
	movapd	.LC5(%rip), %xmm5
	mulpd	%xmm2, %xmm5
	movsd	%xmm1, 32(%rsp)
	movupd	48(%rsp), %xmm4   /* this function was generated by the intrinsic function 					     _mm_loadu_pd */
	movsd	%xmm7, 40(%rsp)
	movupd	64(%rsp), %xmm3   /* this function was generated by the intrinsic function 					     _mm_loadu_pd */
	addpd	%xmm5, %xmm4
	xorpd	%xmm5, %xmm5
	movsd	%xmm6, 8(%rsp)
	mulpd	%xmm5, %xmm2
	addpd	%xmm2, %xmm3
	movupd	32(%rsp), %xmm2
	mulpd	%xmm2, %xmm5
	mulpd	.LC6(%rip), %xmm2
	addpd	%xmm5, %xmm4
	addpd	%xmm2, %xmm3
	movupd	%xmm4, 48(%rsp)
	movapd	%xmm1, %xmm2
	movupd	%xmm3, 64(%rsp)
	movapd	%xmm6, %xmm3
	movsd	64(%rsp), %xmm5
	movsd	48(%rsp), %xmm4
	call	printf
	movsd	8(%rsp), %xmm6
	movl	$.LC8, %edi
	movsd	72(%rsp), %xmm5
	movl	$6, %eax
	movsd	56(%rsp), %xmm4
	movsd	40(%rsp), %xmm1
	movapd	%xmm6, %xmm2
	movsd	24(%rsp), %xmm0
	movsd	.LC1(%rip), %xmm3
	call	printf
	xorl	%eax, %eax
	addq	$88, %rsp
	.cfi_def_cfa_offset 8
	ret
	.cfi_endproc
.LFE532:
	.size	main, .-main
	.section	.rodata.cst8,"aM",@progbits,8
	.align 8
.LC0:
	.long	0
	.long	1072693248
	.align 8
.LC1:
	.long	0
	.long	1073741824
	.align 8
.LC2:
	.long	0
	.long	1074266112
	.align 8
.LC3:
	.long	0
	.long	1074790400
	.section	.rodata.cst16,"aM",@progbits,16
	.align 16
.LC5:
	.long	0
	.long	1074266112
	.long	0
	.long	1074266112
	.align 16
.LC6:
	.long	0
	.long	1073741824
	.long	0
	.long	1073741824
	.ident	"GCC: (GNU) 4.8.5 20150623 (Red Hat 4.8.5-44)"
	.section	.note.GNU-stack,"",@progbits
